### ISSUE TITLE
似たコードの違いってなんでしょうか

### ISSUE THREAD

**Issue by msnzk** [FrontEndCircle-crs/fullpath_smoothscroll#1]
コーポレートやカードローンでも似た感じのスムーススクロールを使っているんですが、
具体的に違うところって、どんなところどうなんでしょうか。

コーポレート
```
$("a[href^=#]").click(function(){
	 href= $(this).attr("href");
	var target = $(href === "#" || href === "" ? "html" : href);
	var position = target.offset().top;
	$("html, body").animate({ scrollTop:position }, 500, "swing");
	return false;
});
```

カードローン
```
// ページ内スクロール
if(location.hash.length > 0) pageScroll($(location.hash));

$('a[href*="#"]' + ':not(a.not-scroll)').bind('click', function() {
	if(location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
		var $target = $(this.hash);

		$target = $target.length && $target || $('[name=' + this.hash.slice(1) +']');
		pageScroll($target);

		return false;
	}
});
```

**Comment by ohtsufumihiro** [comment]
@msnzk 絶対パスでも動くスムーススクロールなのが、こちらのオリジナルです。
コーポレートやカードローンの場合
```$('a[href*="#"]'```や```$("a[href^=#]")```
を指定しているので、html側は
```<a href="#xxxx">```
と指定しないとスムースが動かないと思います。

ですが、こちらのオリジナルJSはhtml側で
```<a href="http://test.co.jp/#xxxx">```や```<a href="#xxxx">```
でもスムーススクロールが動きます。

これによって、何が利点かというと管理画面等のURL形式登録で```http://test.co.jp/#xxxx```を登録してもスムーススクロールが動くということになります。もちろん、管理画面の登録でPHP側で制御することも可能です。#があり、ドメインが同サイトである場合は```http://test.co.jp/```をなくす等。mtoku以外は管理画面で制御しているかと思います。オリジナルJSを表側で入れる事で管理画面側はhtml5のurlチェックだけで済みます。
もう一点は違うサイトや別ページから来た場合でもスムーススクロールが動きます。

現在のJSは絶対パスだけですが、こちらのJSを応用(if文で二つくらい条件を追加)することにより絶対パス、相対パス、#のみでも動くことが出来るようになります。要望がなかった為、絶対パスだけですが・・・。
```
例）
<a href="http://test.co.jp/dir1/#xxxx">
<a href="/dir1/#xxxx">
<a href="#xxxx">
```

**Comment by msnzk** [comment]
@ohtsufumihiro なるほど！細かくありがとうございます。
「絶対パスでスクロール」の意味と利点を理解できました。

パフォーマンスの点だとPHP側で処理してもらった方が速そうですが、
ロジックいじらないで済むのが良いですね。

**Comment by ohtsufumihiro** [comment]
@msnzk 今の会社も以前の会社も「ブラウザのURLをコピペしたいです」とか「別ページからのリンクでもスムーススクロールを動かしてほしい」とか必ず言われるので、そういった時は参考にして頂ければ。
因みにmsnzkさんも過去に絶賛していましたよ。別ページからのリンクでも動くんですねって。ｗｗ
